#!/usr/bin/env node

import os from 'node:os';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

import fs from 'fs-extra';
import { execa } from 'execa';
import ora from 'ora';
import pc from 'picocolors';
import prompts from 'prompts';
import { Command } from 'commander';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const DEFAULTS = {
  template: 'webview',
  minSdk: 27,
  targetSdk: 27,
  compileSdk: 27,
  agpVersion: '9.1.1',
  gradleVersion: '9.3.1',
  javaVersion: '17',
  webUrl: 'https://example.com'
};

const TEMPLATES = {
  webview: {
    files: {
      'settings.gradle': `pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = '__APP_NAME__'
include(':app')
`,
      'build.gradle': `plugins {
    id 'com.android.application' version '__AGP_VERSION__' apply false
}
`,
      'gradle.properties': `org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
`,
      'app/build.gradle': `plugins {
    id 'com.android.application'
}

android {
    namespace '__PACKAGE__'
    compileSdk __COMPILE_SDK__

    defaultConfig {
        applicationId '__PACKAGE__'
        minSdk __MIN_SDK__
        targetSdk __TARGET_SDK__
        versionCode 1
        versionName '1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
}
`,
      'app/src/main/AndroidManifest.xml': `<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="__PACKAGE__">

__PERMISSIONS__

    <application
        android:allowBackup="true"
        android:label="@string/app_name"
        android:supportsRtl="true">
        <activity
            android:name=".MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>
`,
      'app/src/main/res/values/strings.xml': `<resources>
    <string name="app_name">__APP_NAME__</string>
</resources>
`,
      'app/src/main/res/layout/activity_main.xml': `<WebView xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/webview"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />
`,
      'app/src/main/java/__PACKAGE_PATH__/MainActivity.java': `package __PACKAGE__;

import android.app.Activity;
import android.os.Build;
import android.os.Bundle;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.webkit.WebViewClient;

public class MainActivity extends Activity {

    private WebView webView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        webView = findViewById(R.id.webview);

        WebSettings settings = webView.getSettings();
        settings.setJavaScriptEnabled(true);
        settings.setDomStorageEnabled(true);
        settings.setAllowFileAccess(true);
        settings.setAllowContentAccess(true);

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            settings.setMixedContentMode(WebSettings.MIXED_CONTENT_ALWAYS_ALLOW);
        }

        webView.setWebViewClient(new WebViewClient());
        webView.loadUrl('__WEB_URL__');
    }

    @Override
    public void onBackPressed() {
        if (webView != null && webView.canGoBack()) {
            webView.goBack();
            return;
        }
        super.onBackPressed();
    }
}
`,
      'README.md': `# __APP_NAME__

Generated by japkgen.

## Build
\`\`\`bash
./gradlew assembleDebug
\`\`\`
`
    }
  },

  native: {
    files: {
      'settings.gradle': `pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = '__APP_NAME__'
include(':app')
`,
      'build.gradle': `plugins {
    id 'com.android.application' version '__AGP_VERSION__' apply false
}
`,
      'gradle.properties': `org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
`,
      'app/build.gradle': `plugins {
    id 'com.android.application'
}

android {
    namespace '__PACKAGE__'
    compileSdk __COMPILE_SDK__

    defaultConfig {
        applicationId '__PACKAGE__'
        minSdk __MIN_SDK__
        targetSdk __TARGET_SDK__
        versionCode 1
        versionName '1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
}
`,
      'app/src/main/AndroidManifest.xml': `<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="__PACKAGE__">

__PERMISSIONS__

    <application
        android:allowBackup="true"
        android:label="@string/app_name"
        android:supportsRtl="true">
        <activity
            android:name=".MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>
`,
      'app/src/main/res/values/strings.xml': `<resources>
    <string name="app_name">__APP_NAME__</string>
</resources>
`,
      'app/src/main/res/layout/activity_main.xml': `<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="center"
    android:orientation="vertical"
    android:padding="24dp">

    <TextView
        android:id="@+id/message"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Hello from __APP_NAME__!"
        android:textSize="24sp" />
</LinearLayout>
`,
      'app/src/main/java/__PACKAGE_PATH__/MainActivity.java': `package __PACKAGE__;

import android.app.Activity;
import android.os.Bundle;

public class MainActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }
}
`,
      'README.md': `# __APP_NAME__

Generated by japkgen.

## Build
\`\`\`bash
./gradlew assembleDebug
\`\`\`
`
    }
  }
};

function normalizePathValue(input = '') {
  return String(input)
    .replaceAll('\\', '/')
    .replace(/\/+/g, '/')
    .replace(/^\.\//, '')
    .replace(/^\//, '');
}

function toPackagePath(pkg = '') {
  return normalizePathValue(String(pkg).trim().replaceAll('.', '/'));
}

function applyTemplate(content, vars) {
  return String(content).replace(/__([A-Z0-9_]+)__/g, (match, key) => {
    return Object.prototype.hasOwnProperty.call(vars, key) ? String(vars[key]) : match;
  });
}

function parseList(input = '') {
  return String(input)
    .split(',')
    .map((v) => v.trim())
    .filter(Boolean);
}

function parsePermissions(input = '') {
  return parseList(input).map((perm) => {
    if (perm.startsWith('android.permission.')) return perm;
    return `android.permission.${perm}`;
  });
}

async function writeFileEnsured(filePath, content) {
  await fs.ensureDir(path.dirname(filePath));
  await fs.writeFile(filePath, content, 'utf8');
}

async function templateExists(projectDir) {
  const gradlew = process.platform === 'win32'
    ? path.join(projectDir, 'gradlew.bat')
    : path.join(projectDir, 'gradlew');

  const wrapperJar = path.join(projectDir, 'gradle', 'wrapper', 'gradle-wrapper.jar');
  const wrapperProps = path.join(projectDir, 'gradle', 'wrapper', 'gradle-wrapper.properties');

  return (
    (await fs.pathExists(gradlew)) &&
    (await fs.pathExists(wrapperJar)) &&
    (await fs.pathExists(wrapperProps))
  );
}

async function bootstrapGradleWrapper(projectDir, gradleVersion) {
  if (await templateExists(projectDir)) return;

  const gradleBin = process.platform === 'win32' ? 'gradle.bat' : 'gradle';

  const tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'japkgen-wrapper-'));
  const spinner = ora(`Bootstrapping Gradle wrapper ${gradleVersion}`).start();

  try {
    await writeFileEnsured(
      path.join(tempDir, 'settings.gradle'),
      `rootProject.name = 'wrapper-bootstrap'\n`
    );
    await writeFileEnsured(path.join(tempDir, 'build.gradle'), `\n`);

    await execa(
      gradleBin,
      ['wrapper', '--gradle-version', String(gradleVersion), '--distribution-type', 'bin'],
      {
        cwd: tempDir,
        stdio: 'inherit'
      }
    );

    await fs.ensureDir(path.join(projectDir, 'gradle', 'wrapper'));

    const copies = [
      ['gradlew', 'gradlew'],
      ['gradlew.bat', 'gradlew.bat'],
      ['gradle/wrapper/gradle-wrapper.jar', 'gradle/wrapper/gradle-wrapper.jar'],
      ['gradle/wrapper/gradle-wrapper.properties', 'gradle/wrapper/gradle-wrapper.properties']
    ];

    for (const [srcRel, dstRel] of copies) {
      await fs.copy(path.join(tempDir, srcRel), path.join(projectDir, dstRel), {
        overwrite: true
      });
    }

    if (process.platform !== 'win32') {
      await fs.chmod(path.join(projectDir, 'gradlew'), 0o755);
    }

    spinner.succeed('Gradle wrapper ready');
  } catch (error) {
    spinner.fail('Failed to bootstrap Gradle wrapper');
    throw error;
  } finally {
    await fs.remove(tempDir);
  }
}

async function ensureLocalProperties(projectDir) {
  const androidSdkRoot = process.env.ANDROID_SDK_ROOT || process.env.ANDROID_HOME;
  if (!androidSdkRoot) return;

  const localPropsPath = path.join(projectDir, 'local.properties');
  const content = `sdk.dir=${normalizePathValue(androidSdkRoot)}\n`;
  await writeFileEnsured(localPropsPath, content);
}

async function writeTemplateProject(projectDir, templateName, vars) {
  const template = TEMPLATES[templateName];
  if (!template) {
    throw new Error(`Unknown template: ${templateName}`);
  }

  for (const [rawRelativePath, rawContent] of Object.entries(template.files)) {
    const relativePath = applyTemplate(rawRelativePath, vars);
    const outputPath = path.join(projectDir, relativePath);
    const outputContent = applyTemplate(rawContent, vars);
    await writeFileEnsured(outputPath, outputContent);
  }
}

async function pickGenerateOptions(cliOptions) {
  const questions = [];

  if (!cliOptions.name) {
    questions.push({
      type: 'text',
      name: 'name',
      message: 'App name',
      initial: 'app'
    });
  }

  if (!cliOptions.package) {
    questions.push({
      type: 'text',
      name: 'package',
      message: 'Package name',
      initial: 'com.example.app'
    });
  }

  if (!cliOptions.template) {
    questions.push({
      type: 'select',
      name: 'template',
      message: 'Template',
      choices: [
        { title: 'WebView', value: 'webview' },
        { title: 'Native', value: 'native' }
      ],
      initial: 0
    });
  }

  if (cliOptions.minSdk == null) {
    questions.push({
      type: 'number',
      name: 'minSdk',
      message: 'Min SDK',
      initial: DEFAULTS.minSdk
    });
  }

  if (cliOptions.targetSdk == null) {
    questions.push({
      type: 'number',
      name: 'targetSdk',
      message: 'Target SDK',
      initial: DEFAULTS.targetSdk
    });
  }

  if (cliOptions.compileSdk == null) {
    questions.push({
      type: 'number',
      name: 'compileSdk',
      message: 'Compile SDK',
      initial: DEFAULTS.compileSdk
    });
  }

  if ((cliOptions.template || DEFAULTS.template) !== 'native' && !cliOptions.url) {
    questions.push({
      type: 'text',
      name: 'url',
      message: 'WebView URL',
      initial: DEFAULTS.webUrl
    });
  }

  if (!cliOptions.permissions) {
    questions.push({
      type: 'text',
      name: 'permissions',
      message: 'Permissions (comma separated)',
      initial: 'INTERNET'
    });
  }

  const result = questions.length
    ? await prompts(questions, {
        onCancel: () => {
          process.exit(1);
        }
      })
    : {};

  return {
    name: cliOptions.name || result.name,
    package: cliOptions.package || result.package,
    template: cliOptions.template || result.template || DEFAULTS.template,
    minSdk: Number(cliOptions.minSdk ?? result.minSdk ?? DEFAULTS.minSdk),
    targetSdk: Number(cliOptions.targetSdk ?? result.targetSdk ?? DEFAULTS.targetSdk),
    compileSdk: Number(cliOptions.compileSdk ?? result.compileSdk ?? DEFAULTS.compileSdk),
    url: cliOptions.url || result.url || DEFAULTS.webUrl,
    permissions: cliOptions.permissions || result.permissions || 'INTERNET'
  };
}

async function generateProject(cliOptions) {
  const opts = await pickGenerateOptions(cliOptions);

  const projectName = String(opts.name).trim();
  const packageName = String(opts.package).trim();
  const templateName = String(opts.template).trim().toLowerCase();

  if (!projectName) throw new Error('App name is required.');
  if (!packageName) throw new Error('Package name is required.');
  if (!TEMPLATES[templateName]) {
    throw new Error(`Unknown template "${templateName}". Choose webview or native.`);
  }

  const projectDir = path.resolve(process.cwd(), projectName);

  if (await fs.pathExists(projectDir)) {
    const items = await fs.readdir(projectDir);
    if (items.length > 0) {
      throw new Error(`Target directory is not empty: ${projectDir}`);
    }
  }

  await fs.ensureDir(projectDir);

  const permissions = parsePermissions(opts.permissions);
  const permissionLines = permissions
    .map((perm) => `    <uses-permission android:name="${perm}" />`)
    .join('\n');

  const vars = {
    APP_NAME: projectName,
    PACKAGE: packageName,
    PACKAGE_PATH: toPackagePath(packageName),
    MIN_SDK: opts.minSdk,
    TARGET_SDK: opts.targetSdk,
    COMPILE_SDK: opts.compileSdk,
    AGP_VERSION: DEFAULTS.agpVersion,
    GRADLE_VERSION: DEFAULTS.gradleVersion,
    JAVA_VERSION: DEFAULTS.javaVersion,
    WEB_URL: opts.url,
    PERMISSIONS: permissionLines
  };

  const spinner = ora(`Generating ${projectName}`).start();

  try {
    await writeTemplateProject(projectDir, templateName, vars);
    await ensureLocalProperties(projectDir);

    try {
      await bootstrapGradleWrapper(projectDir, DEFAULTS.gradleVersion);
    } catch (error) {
      console.warn(
        pc.yellow(
          '\nWrapper bootstrap skipped or failed. Project is generated, but build command may need system Gradle the first time.\n'
        )
      );
    }

    spinner.succeed(`Project created at ${projectDir}`);
    console.log(pc.cyan(`Template: ${templateName}`));
    console.log(pc.green(`Next: cd ${projectName}`));
    console.log(pc.green(`Build: japkgen build ${projectName}`));
  } catch (error) {
    spinner.fail('Generation failed');
    throw error;
  }
}

async function buildProject(projectDirArg, buildOptions) {
  const projectDir = path.resolve(projectDirArg || process.cwd());
  const variant = String(buildOptions.variant || 'debug').toLowerCase();

  if (!(await fs.pathExists(projectDir))) {
    throw new Error(`Project directory not found: ${projectDir}`);
  }

  await ensureLocalProperties(projectDir);

  const spinner = ora(`Preparing build (${variant})`).start();

  try {
    await bootstrapGradleWrapper(projectDir, buildOptions.gradleVersion || DEFAULTS.gradleVersion);

    const isWindows = process.platform === 'win32';
    const gradlew = isWindows ? 'gradlew.bat' : './gradlew';
    const task = variant === 'release' ? 'assembleRelease' : 'assembleDebug';

    spinner.text = `Running ${task}`;

    await execa(gradlew, [task], {
      cwd: projectDir,
      stdio: 'inherit',
      shell: isWindows
    });

    spinner.succeed(`Build complete: ${task}`);

    const apkPath =
      variant === 'release'
        ? path.join(projectDir, 'app', 'build', 'outputs', 'apk', 'release', 'app-release.apk')
        : path.join(projectDir, 'app', 'build', 'outputs', 'apk', 'debug', 'app-debug.apk');

    console.log(pc.green(`APK path: ${apkPath}`));
  } catch (error) {
    spinner.fail('Build failed');
    throw error;
  }
}

const program = new Command();

program
  .name('japkgen')
  .description('Java APK project generator')
  .version('0.1.0');

program
  .command('new')
  .alias('init')
  .description('Generate a new Android project')
  .option('--name <name>', 'App name')
  .option('--package <package>', 'Package name')
  .option('--template <template>', 'webview or native')
  .option('--min-sdk <number>', 'Min SDK', (v) => Number(v))
  .option('--target-sdk <number>', 'Target SDK', (v) => Number(v))
  .option('--compile-sdk <number>', 'Compile SDK', (v) => Number(v))
  .option('--url <url>', 'WebView URL')
  .option('--permissions <list>', 'Comma separated permissions')
  .action(async (options) => {
    await generateProject(options);
  });

program
  .command('build [projectDir]')
  .description('Build APK in a project directory')
  .option('--variant <variant>', 'debug or release', 'debug')
  .option('--gradle-version <version>', 'Gradle version for wrapper bootstrap', DEFAULTS.gradleVersion)
  .action(async (projectDir, options) => {
    await buildProject(projectDir, options);
  });

program.parseAsync(process.argv).catch((error) => {
  console.error(pc.red(`\n${error.message || error}`));
  process.exit(1);
});